sys:
  name: Espricho
  version: 1.0
  max_log_files: 10
  loader: # make sure there are some files with this name on the configs folder
    - auth # for example the configs of auth must be under the auth section
    - db
    - modules
    - redis
    - elasticsearch
